### ISSUE TITLE
SDK 3.8.0 crashes when opening project

### ISSUE THREAD

**Issue by buschmann23** [sailfishos/sailfish-qtcreator#523]
After updating the SDK to version 3.8.0 it crashes when opening a project in Qt Creator.

GDB backtrace:
```
Thread 1 "qtcreator" received signal SIGSEGV, Segmentation fault.
0x00007fffd5548bb0 in Sfdk::BuildEngine::virtualMachine() const () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/lib/qtcreator/plugins/../libSfdk.so.4
Missing separate debuginfos, use: zypper install libglib-2_0-0-debuginfo-2.70.3-1.1.x86_64
(gdb) bt
#0  0x00007fffd5548bb0 in Sfdk::BuildEngine::virtualMachine() const () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/lib/qtcreator/plugins/../libSfdk.so.4
#1  0x00007fff95bdc255 in ?? () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/lib/qtcreator/plugins/libSailfishOS.so
#2  0x00007ffff5e8b8b7 in void doActivate<false>(QObject*, int, void**) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#3  0x00007fffa3b75480 in ?? () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/lib/qtcreator/plugins/libCMakeProjectManager.so
#4  0x00007ffff5e8b8b7 in void doActivate<false>(QObject*, int, void**) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#5  0x00007ffff5e90487 in QTimer::timeout(QTimer::QPrivateSignal) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#6  0x00007ffff5e907e8 in QTimer::timerEvent(QTimerEvent*) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#7  0x00007ffff5e82313 in QObject::event(QEvent*) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#8  0x00007ffff718ba5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Widgets.so.5
#9  0x00007ffff71928ff in QApplication::notify(QObject*, QEvent*) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Widgets.so.5
#10 0x00007ffff5e4e223 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#11 0x00007ffff5eafb29 in QTimerInfoList::activateTimers() () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#12 0x00007ffff5eb02f1 in timerSourceDispatch(_GSource*, int (*)(void*), void*) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#13 0x00007ffff4411d5f in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#14 0x00007ffff44120e8 in ?? () from /lib64/libglib-2.0.so.0
#15 0x00007ffff441219f in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#16 0x00007ffff5eb069c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#17 0x00007ffff5e4caaa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#18 0x00007ffff5e562a7 in QCoreApplication::exec() () from /home/buschmann/Dokumente/Entwicklung/SailfishOS/bin/../lib/Qt/lib/libQt5Core.so.5
#19 0x000055555540ad6e in ?? ()
#20 0x00007ffff57385c0 in __libc_start_call_main (main=main@entry=0x555555408400, argc=argc@entry=1, argv=argv@entry=0x7fffffffdb78) at ../sysdeps/nptl/libc_start_call_main.h:58
#21 0x00007ffff573867c in __libc_start_main_impl (main=0x555555408400, argc=1, argv=0x7fffffffdb78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdb68)
    at ../csu/libc-start.c:409
#22 0x000055555540b85a in ?? ()
```

My environment:
OS: openSUSE Tumbleweed
Linux: 5.16.8
Desktop Environment: KDE Plasma 5.24
Virtualization: VirtualBox 6.1.32

**Comment by buschmann23** [comment]
Deleting build directory and CMakeLists.txt.user file fixed it for now.

**Comment by vigejolla** [comment]
> Deleting build directory and CMakeLists.txt.user file fixed it for now.

Not exactly surprising. It would have been nice to know what exactly it was that was causing the crash, but I guess you didn't save the build directory and CMakeLists.txt.user contents?

**Comment by buschmann23** [comment]
Ouh, sorry, no.

**Comment by vigejolla** [comment]
I tried to reproduce again by following your steps, i.e. updating from 3.7.4 to 3.8.3 and opening a cmake project which was created using the older version. Still no crash. I'll close this now, let's reopen if we get new information.
